apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: default
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    run: demo
  type: ClusterIP
status:
  loadBalancer: {}
