apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: default
spec:
  template:
    spec:
      containers:
        - image: docker.io/csantanapr/knative-tekton
          imagePullPolicy: Always
          env:
            - name: TARGET
              value: Welcome Mariane to the Cloud-Native Summit today
