apiVersion: v1
kind: Service
metadata:
  name: demo
  namespace: default
spec:
 template:
  spec:
    containers:
      - image: docker.io/csantanapr/knative-tekton
        imagePullPolicy: Always
        env:
          - name: TARGET
            value: Welcome Mariane to the Cloud-Native Summit today
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    run: demo
  type: ClusterIP
status:
  loadBalancer: {}
